### PR TITLE
Faster dotnetcore, add parallel, better timing

### PR DESCRIPTION
**Pull request by benaadams**
Added Parallel, Single threaded Async; multithreaded Async and ValueTask Async

If you use the Release config

```
dotnet run --configuration Release
```

or compile it in release mode...

```
dotnet compile --configuration Release -o bin
bin\dnx
```

The results are (Win10 on iMac Intel i5 @ 2.9GHz)

```
Arch 64 bit - Cores 4
499999500000
1 Thread - Sync: 5.756ms
499999500000
1 Thread - Async: 146.579ms
499999500000
1 Thread - ValueTask Async: 16.917ms
499999500000
Parallel Async: 86.191ms
499999500000
Parallel - ValueTask Async: 4.988ms
499999500000
Parallel Sync: 1.661ms
```

Debug mode matches the current results

```
Arch 64 bit - Cores 4
499999500000
1 Thread - Sync: 42.653ms
499999500000
1 Thread - Async: 186.333ms
499999500000
1 Thread - ValueTask Async: 64.792ms
499999500000
Parallel Async: 84.977ms
499999500000
Parallel - ValueTask Async: 19.903ms
499999500000
Parallel Sync: 13.490ms
```

### CODE REVIEW

**Comment by benaadams** [comment]
Example output 
```
Arch 64 bit
499999500000
1 Thread - Sync: 44.023ms
499999500000
1 Thread - Async: 186.796ms
499999500000
Parallel Async: 90.184ms
499999500000
Parallel Sync: 13.680ms
```

**Comment by benaadams** [comment]
With the new ValueTask async
```
Arch 64 bit
499999500000
1 Thread - Sync: 42.482ms
499999500000
1 Thread - Async: 186.755ms
499999500000
1 Thread - ValueTask Async: 65.250ms
499999500000
Parallel Async: 86.657ms
499999500000
Parallel - ValueTask Async: 20.014ms
499999500000
Parallel Sync: 13.094ms
```

**Comment by benaadams** [comment]
Also if you actually compile it in release mode...
```
dotnet compile --configuration Release -o bin
bin\dnx
```
The results are
```
Arch 64 bit - Cores 4
499999500000
1 Thread - Sync: 5.756ms
499999500000
1 Thread - Async: 146.579ms
499999500000
1 Thread - ValueTask Async: 16.917ms
499999500000
Parallel Async: 86.191ms
499999500000
Parallel - ValueTask Async: 4.988ms
499999500000
Parallel Sync: 1.661ms
```

**Comment by Jetski5822** [comment]
whoah, didn't realize what ValueTask Async gave us! +1

**Pull request merged**
