### PR TITLE
Added node-bluebird

### PR DESCRIPTION
**Pull request by spion**
.NET on my machine:

```
24906 % dotnet run
Project dnx (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.
499999500000
Sync sec: 0.162
499999500000
Async sec: 0.482
```

node-bluebird:

```
24908 % node skynet
499999500000
regular: 365.884ms
499999500000
warmed-up: 261.911ms
```

### CODE REVIEW

**Comment by wizzard0** [comment]
Doesnt Node have a builtin Promise for quite some time now? :)

**Comment by wizzard0** [comment]
Oh I see, it goes OOM with the native Promise impl. Funny.

**Comment by spion** [comment]
@wizzard0 yeah, native promises really are subpar for now :(

**Comment by petkaantonov** [comment]
> yeah, native promises really are subpar for now :(

[A V8 maintainer says this about ES6 features in general](https://groups.google.com/forum/#!msg/strengthen-js/ojj3TDxbHpQ/5ENNAiUzEgAJ):

> ES6 performance sucks! Strong mode is a mode for ES6, you cannot use it without using various ES6 features. However, idiomatic ES6 code currently is substantially slower than ES5, across all browsers -- easily by 2x, often by 10x or more. Due to the sheer size of ES6, plus a number of unfortunate design choices, it will likely take years until implementations catch up with ES5 optimisations, and the hundreds of man years that went into those. Until then, strong mode is not going to be an attractive target.

**Comment by petkaantonov** [comment]
This will probably cause a downward spiral where people won't use es6 cos it's slow and the optimizations are not done because people don't use the features...

**Pull request merged**
