### PR TITLE
Re-writing Haskell version for code clarity and major speed improvements

### PR DESCRIPTION
**Pull request by ixmatus**
Core i7 Linux Laptop results:

| Old | New |
| --- | --- |
| 499999500000 in 2.57968s | 499999500000 in 0.617s |

### CODE REVIEW

**Comment by mijoharas** [comment]
You couldn't explain why you think you get the speed improvements that you do with these optimisations, could you?

**Comment by ixmatus** [comment]
@mijoharas are you asking me to explain it?

**Comment by mijoharas** [comment]
@ixmatus yes, if it's not too much trouble. Just interested as a relative haskell beginner. I guess I'm mainly asking about the main points, what informed the decision to switch from using Chan to using Async.

**Comment by osa1** [comment]
This is faster because you're not doing the same thing! The wrong part is here:

``` haskell
supervisor n s d = wait =<< async (worker n s d)
```

Then in the worker:

``` haskell
worker :: Int -> Int -> Int -> IO Int
worker num size dv
    | size == 1 = return num
    | otherwise = sum <$> forM [0..dv-1] spawnChild
```

Basically you're sequentially spawning threads and waiting for results. This is different than how the original version worked. You should have done this instead:

``` haskell
worker :: Int -> Int -> Int -> IO Int
worker num size dv
    | size == 1 = return num
    | otherwise = sum <$> mapConcurrently mkChild [0..dv-1]
  where
    sizeDiv = size `quot` dv
    subNum i = num + i * sizeDiv
    mkChild (subNum -> n) = worker n sizeDiv dv

main :: IO ()
main = do
    start  <- getCurrentTime
    result <- wait =<< async (worker 0 1000000 10)
    end    <- getCurrentTime

    putStrLn $ concat ["Result: ", show result, " in ", show (diffUTCTime end start)]
```

Which is more than 2x slower.

**Comment by ixmatus** [comment]
@osa1 good catch - the `wait` is blocking in the `forM` which doesn't really test GHC's scheduler very well (unlike the original which is similar to your revision using `mapConcurrently`).

@mijoharas there you have it :)

**Comment by mijoharas** [comment]
Thanks!

**Comment by ixmatus** [comment]
Closing this PR because my version is actually quite a bit slower than the original using @osa1's revisions!

**Pull request closed without merging**
